<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="6.0.4" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.0" />
		<PackageReference Include="NUnit" Version="4.3.2" />
		<PackageReference Include="NUnit.Analyzers" Version="4.7.0" />
		<PackageReference Include="NUnit3TestAdapter" Version="5.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Software.Archiver\Software.Archiver.csproj" />
		<ProjectReference Include="..\Software.Core\Software.Core.csproj" />
		<ProjectReference Include="..\Software.FileCommander\Software.FileCommander.csproj" />
		<ProjectReference Include="..\Software.MediaPlayer\Software.MediaPlayer.csproj" />
		<ProjectReference Include="..\Software.MergeTool\Software.MergeTool.csproj" />
		<ProjectReference Include="..\Software.Notepad\Software.Notepad.csproj" />
		<ProjectReference Include="..\Software.PasswordManager\Software.PasswordManager.csproj" />
		<ProjectReference Include="..\Software.Sheets\Software.Sheets.csproj" />
		<ProjectReference Include="..\Software.TextProcessor\Software.TextProcessor.csproj" />
		<ProjectReference Include="..\Software.WebBrowser\Software.WebBrowser.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="NUnit.Framework" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Fixtures\simple.doc" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

</Project>
